version: '3'

#NETWORK
networks: 
  database_my-network:
    external: true

#SERVICES
services:
  #REDMINE
  redmine:
    container_name: redmine
    image: redmine:latest
    restart: always
    networks: 
      - database_my-network
    volumes: 
      - ./redmine:/home/redmine:z
    ports:
      - 6677:3000 #redmine port
    environment:
      REDMINE_DB_MYSQL: mysql-product
      REDMINE_DB_USERNAME: root
      REDMINE_DB_PASSWORD: admin
      REDMINE_DB_DATABASE: redmine
  #GITEA
  gitea:
    container_name: gitea-product
    image: gitea/gitea:latest
    hostname: gitea
    restart: always
    networks: 
      - database_my-network
    ports:
      - 3000:3000
      - 22:22
  #container Camunda
  camunda:
    image: camunda/camunda-bpm-platform
    container_name: camunda
    networks: 
      - database_my-network
    ports:
      - '1313:8080'
    environment:
      DB_DRIVER: com.mysql.jdbc.Driver
      DB_URL: 'jdbc:mysql://mysql-db:3306/camunda?autoReconnect=true'
      DB_USERNAME: root
      DB_PASSWORD: admin
   